In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_excel('/content/drive/MyDrive/Trek AI/Y2-Data.xlsx')

In [4]:
# Kolom yang akan digunakan untuk klasifikasi
grading_columns = ['PATHOLOGY MARK', 'MICROBIOLOGY MARK', 'PHARMACOLOGY MARK', 'DENTAL MATERIAL SCIENCE MARK ']

# Fungsi untuk mengklasifikasikan nilai menjadi kategori
def classify_grades(score):
    # Mengonversi nilai ke tipe data numerik jika belum
    try:
        score = float(score)
    except ValueError:
        return 'Invalid Score'  # Atau tindakan yang sesuai jika nilai tidak dapat dikonversi

    if score >= 75:
        return 'A'
    elif 60 <= score < 75:
        return 'B'
    elif 50 <= score < 60:
        return 'C'
    else:
        return 'F'

# Iterasi melalui kolom-kolom yang akan dijadikan dasar klasifikasi
for column in grading_columns:
    # Membuat kolom baru dengan nama yang dihasilkan dari kolom asli ditambah '_GRADE'
    new_column_name = column + '_GRADE'
    df[new_column_name] = df[column].apply(classify_grades)

# Tampilkan DataFrame yang sudah dimodifikasi
print(df)


    STUDENT'S IDENTITY NO.   LAST DIGIT MATRIC NO.  AGE DURING ADMISSION  \
0                  12-13-01                      8                    21   
1                  12-13-02                      6                    20   
2                  12-13-03                      6                    20   
3                  12-13-04                      4                    20   
4                  12-13-05                      6                    20   
..                      ...                    ...                   ...   
246                16-17-51                      5                    20   
247                16-17-52                      4                    20   
248                16-17-53                      4                    20   
249                16-17-55                      2                    20   
250                16-17-56                      4                    19   

    BIRTH DATE MIDDLE IC NO.          DISTRICT POSCODE       STATE   COUNTRY  \
0      

In [5]:
df.columns

Index(['STUDENT'S IDENTITY NO. ', 'LAST DIGIT MATRIC NO.',
       'AGE DURING ADMISSION', 'BIRTH DATE', 'MIDDLE IC NO.', 'DISTRICT',
       'POSCODE', 'STATE', 'COUNTRY', 'PRE-UNIVERSITY', 'TOTAL_SEM',
       'AVERAGE_CGPA', 'FINAL_CGPA', 'ANATOMY MARK', 'ANATOMY STATUS',
       'PHYSIOLOGY MARK', 'PHYSIOLOGY STATUS', 'BIOCHEMISTRY MARK',
       'BIOCHEMISTRY STATUS', 'ORAL BIOLOGY MARK', 'ORAL BIOLOGY STATUS',
       'PATHOLOGY MARK', 'PATHOLOGY STATUS', 'MICROBIOLOGY MARK',
       'MICROBIOLOGY STATUS', 'PHARMACOLOGY MARK', 'PHARMACOLOGY STATUS',
       'DENTAL MATERIAL SCIENCE MARK ', 'DENTAL MATERIAL SCIENCE STATUS',
       'Batch', 'REPEAT PAPER', 'GENDER_MALE', 'PATHOLOGY MARK_GRADE',
       'MICROBIOLOGY MARK_GRADE', 'PHARMACOLOGY MARK_GRADE',
       'DENTAL MATERIAL SCIENCE MARK _GRADE'],
      dtype='object')

In [6]:
df.isnull().sum()

STUDENT'S IDENTITY NO.                 0
LAST DIGIT MATRIC NO.                  0
AGE DURING ADMISSION                   0
BIRTH DATE                             0
MIDDLE IC NO.                          0
DISTRICT                               0
POSCODE                                0
STATE                                  0
COUNTRY                                0
PRE-UNIVERSITY                         0
TOTAL_SEM                              0
AVERAGE_CGPA                           0
FINAL_CGPA                             0
ANATOMY MARK                           0
ANATOMY STATUS                         0
PHYSIOLOGY MARK                        0
PHYSIOLOGY STATUS                      0
BIOCHEMISTRY MARK                      0
BIOCHEMISTRY STATUS                    0
ORAL BIOLOGY MARK                      0
ORAL BIOLOGY STATUS                    0
PATHOLOGY MARK                         0
PATHOLOGY STATUS                       0
MICROBIOLOGY MARK                      0
MICROBIOLOGY STA

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 36 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   STUDENT'S IDENTITY NO.               251 non-null    object 
 1   LAST DIGIT MATRIC NO.                251 non-null    int64  
 2   AGE DURING ADMISSION                 251 non-null    int64  
 3   BIRTH DATE                           251 non-null    object 
 4   MIDDLE IC NO.                        251 non-null    object 
 5   DISTRICT                             251 non-null    object 
 6   POSCODE                              251 non-null    object 
 7   STATE                                251 non-null    object 
 8   COUNTRY                              251 non-null    object 
 9   PRE-UNIVERSITY                       251 non-null    object 
 10  TOTAL_SEM                            251 non-null    int64  
 11  AVERAGE_CGPA                    

In [8]:
df.head()

STUDENT'S IDENTITY NO.   LAST DIGIT MATRIC NO.  AGE DURING ADMISSION  \
0                12-13-01                      8                    21   
1                12-13-02                      6                    20   
2                12-13-03                      6                    20   
3                12-13-04                      4                    20   
4                12-13-05                      6                    20   

  BIRTH DATE MIDDLE IC NO.    DISTRICT POSCODE     STATE   COUNTRY  \
0     911122            14  KOTA BHARU   43000  SELANGOR  MALAYSIA   
1     920816             3      BACHOK   16370  KELANTAN  MALAYSIA   
2     920522             6    JERANTUT   27020    PAHANG  MALAYSIA   
3     920625             8     PUCHONG   47100  SELANGOR  MALAYSIA   
4     920126            10      KAJANG   43000  SELANGOR  MALAYSIA   

  PRE-UNIVERSITY  ...  PHARMACOLOGY STATUS  DENTAL MATERIAL SCIENCE MARK   \
0       CFS IIUM  ...                 PASS                      52.837500   
1       CFS IIUM  ...                 FAIL                      59.316667   
2       CFS IIUM  ...                 PASS                      54.875000   
3       CFS IIUM  ...                 PASS                      59.625000   
4       CFS IIUM  ...                 PASS                      59.629167   

   DENTAL MATERIAL SCIENCE STATUS               Batch REPEAT PAPER  \
0                            PASS  batch1213_combined           NO   
1                            PASS  batch1213_combined           NO   
2                            PASS  batch1213_combined           NO   
3                            PASS  batch1213_combined           NO   
4                            PASS  batch1213_combined           NO   

   GENDER_MALE PATHOLOGY MARK_GRADE  MICROBIOLOGY MARK_GRADE  \
0            0                    C                        C   
1            0                    F                        C   
2            0                    F                        C   
3            0                    C                        B   
4            0                    C                        F   

  PHARMACOLOGY MARK_GRADE  DENTAL MATERIAL SCIENCE MARK _GRADE  
0                       C                                    C  
1                       F                                    C  
2                       C                                    C  
3                       C                                    C  
4                       C                                    C  

[5 rows x 36 columns]

In [9]:
df.columns

Index(['STUDENT'S IDENTITY NO. ', 'LAST DIGIT MATRIC NO.',
       'AGE DURING ADMISSION', 'BIRTH DATE', 'MIDDLE IC NO.', 'DISTRICT',
       'POSCODE', 'STATE', 'COUNTRY', 'PRE-UNIVERSITY', 'TOTAL_SEM',
       'AVERAGE_CGPA', 'FINAL_CGPA', 'ANATOMY MARK', 'ANATOMY STATUS',
       'PHYSIOLOGY MARK', 'PHYSIOLOGY STATUS', 'BIOCHEMISTRY MARK',
       'BIOCHEMISTRY STATUS', 'ORAL BIOLOGY MARK', 'ORAL BIOLOGY STATUS',
       'PATHOLOGY MARK', 'PATHOLOGY STATUS', 'MICROBIOLOGY MARK',
       'MICROBIOLOGY STATUS', 'PHARMACOLOGY MARK', 'PHARMACOLOGY STATUS',
       'DENTAL MATERIAL SCIENCE MARK ', 'DENTAL MATERIAL SCIENCE STATUS',
       'Batch', 'REPEAT PAPER', 'GENDER_MALE', 'PATHOLOGY MARK_GRADE',
       'MICROBIOLOGY MARK_GRADE', 'PHARMACOLOGY MARK_GRADE',
       'DENTAL MATERIAL SCIENCE MARK _GRADE'],
      dtype='object')

In [10]:
# Fungsi untuk mengubah nilai ke float dengan menangani kasus '79>80'
def convert_to_float(value):
    try:
        # Jika nilai dapat diubah menjadi float, kembalikan float dari nilai tersebut
        return float(value)
    except ValueError:
        # Jika terjadi ValueError, berarti nilai memiliki format seperti '79>80'
        # Ambil nilai pertama dari format tersebut (sampai karakter '>') dan kembalikan float-nya
        return float(value.split('>')[0])

# Terapkan fungsi convert_to_float pada kolom 'PHYSIOLOGY MARK'
df['PHYSIOLOGY MARK'] = df['PHYSIOLOGY MARK'].apply(convert_to_float)

# Terapkan fungsi convert_to_float pada kolom 'DENTAL MATERIAL SCIENCE MARK'
df['DENTAL MATERIAL SCIENCE MARK '] = df['DENTAL MATERIAL SCIENCE MARK '].apply(convert_to_float)


In [11]:
from sklearn.feature_selection import SelectKBest, f_classif

x = df.drop(["STUDENT'S IDENTITY NO. ", 'ANATOMY STATUS', 'PHYSIOLOGY STATUS', 'BIOCHEMISTRY STATUS',
             'ORAL BIOLOGY STATUS', 'PATHOLOGY MARK', 'PATHOLOGY STATUS', 'Batch', 'REPEAT PAPER',
             'MICROBIOLOGY MARK', 'MICROBIOLOGY STATUS', 'PHARMACOLOGY MARK',
             'PHARMACOLOGY STATUS', 'DENTAL MATERIAL SCIENCE MARK ',
             'DENTAL MATERIAL SCIENCE STATUS', 'BIRTH DATE','MIDDLE IC NO.',
             'DISTRICT','POSCODE', 'STATE', 'COUNTRY', 'PRE-UNIVERSITY','LAST DIGIT MATRIC NO.', 'GENDER_MALE', 'PATHOLOGY MARK_GRADE',
             'MICROBIOLOGY MARK_GRADE', 'PHARMACOLOGY MARK_GRADE', 'DENTAL MATERIAL SCIENCE MARK _GRADE'], axis=1)
y = df['MICROBIOLOGY MARK_GRADE']

k_best = 4  # Ganti dengan jumlah fitur terbaik yang ingin Anda pilih
selector = SelectKBest(score_func=f_classif, k=k_best)
x_new = selector.fit_transform(x, y)

# Menampilkan fitur terpilih
selected_features = x.columns[selector.get_support()]
print("Selected Features:", selected_features)

Selected Features: Index(['ANATOMY MARK', 'PHYSIOLOGY MARK', 'BIOCHEMISTRY MARK',
       'ORAL BIOLOGY MARK'],
      dtype='object')


In [12]:
y = df['MICROBIOLOGY MARK_GRADE']
y.value_counts()

MICROBIOLOGY MARK_GRADE
B    130
C     98
A     16
F      7
Name: count, dtype: int64

In [13]:
# Memisahkan data menjadi data training dan data testing menjadi 60% data training, 40% data testing
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.4,
                                                   random_state = 2022)

In [14]:
y_train.value_counts()

MICROBIOLOGY MARK_GRADE
B    79
C    60
A    10
F     1
Name: count, dtype: int64

In [15]:
y_test.value_counts()

MICROBIOLOGY MARK_GRADE
B    51
C    38
F     6
A     6
Name: count, dtype: int64

In [16]:
print(x_test)

[[63.38529412 64.47861842 65.75157658 64.72349102]
 [63.41333333 59.46568627 58.59117647 63.81271639]
 [60.19457071 60.66666667 56.1375     68.26622309]
 [62.62867647 70.27006579 71.87038288 62.8614505 ]
 [67.1503268  70.01328947 68.62520646 74.29053693]
 [67.79176471 57.07083333 63.32352941 66.19661835]
 [70.93337418 77.55785088 67.66426426 68.26110798]
 [61.67920752 69.59298246 56.8285473  66.84137457]
 [42.03786392 42.91585639 52.46934524 47.26934524]
 [63.11038324 59.31666667 52.39583333 60.4358453 ]
 [38.         53.65394737 52.15242117 50.        ]
 [53.8868984  48.25       49.73333333 51.64180622]
 [54.91568627 55.83970588 50.         62.82614706]
 [54.43219024 54.1132971  60.52202381 59.78079574]
 [56.30980392 62.42855392 58.2754902  65.78843627]
 [53.32773321 51.50833333 58.02083333 57.63460925]
 [54.28539506 50.         56.56160714 55.48265977]
 [64.38919781 62.16540843 66.10267857 60.24478383]
 [57.65437093 62.14708827 64.59345238 64.7162594 ]
 [75.18647504 61.9        66.30

###LOGISTIC REGRESSION

In [17]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix

# Model Development
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)

y_pred = log_reg.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.00      0.00      0.00         6
           B       0.52      0.90      0.66        51
           C       0.45      0.13      0.20        38
           F       0.00      0.00      0.00         6

    accuracy                           0.50       101
   macro avg       0.24      0.26      0.22       101
weighted avg       0.43      0.50      0.41       101

[[ 0  6  0  0]
 [ 0 46  5  0]
 [ 0 32  5  1]
 [ 1  4  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


###DECISION TREE

In [18]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(random_state= 2022)
clf = clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       1.00      0.17      0.29         6
           B       0.72      0.71      0.71        51
           C       0.60      0.79      0.68        38
           F       0.00      0.00      0.00         6

    accuracy                           0.66       101
   macro avg       0.58      0.42      0.42       101
weighted avg       0.65      0.66      0.63       101

[[ 1  4  1  0]
 [ 0 36 15  0]
 [ 0  8 30  0]
 [ 0  2  4  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###RANDOM FOREST

In [19]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state= 2022)
clf = clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       1.00      0.17      0.29         6
           B       0.63      0.67      0.65        51
           C       0.52      0.63      0.57        38
           F       0.00      0.00      0.00         6

    accuracy                           0.58       101
   macro avg       0.54      0.37      0.38       101
weighted avg       0.57      0.58      0.56       101

[[ 1  4  1  0]
 [ 0 34 17  0]
 [ 0 14 24  0]
 [ 0  2  4  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Definisikan model Naive Bayes
naive_bayes_model = GaussianNB()

# Parameter yang ingin dioptimalkan (hanya var_smoothing pada Gaussian Naive Bayes)
param_grid = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(naive_bayes_model, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_naive_bayes_model = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_naive_bayes_model.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_naive_bayes_model.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Best Parameters: {'var_smoothing': 1e-09}
Classification Report:
               precision    recall  f1-score   support

           A       0.67      0.67      0.67         6
           B       0.72      0.55      0.62        51
           C       0.52      0.76      0.62        38
           F       0.00      0.00      0.00         6

    accuracy                           0.60       101
   macro avg       0.48      0.49      0.48       101
weighted avg       0.60      0.60      0.59       101

Confusion Matrix:
 [[ 4  2  0  0]
 [ 2 28 21  0]
 [ 0  9 29  0]
 [ 0  0  6  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no pre

###SVM

In [21]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           A       1.00      0.17      0.29         6
           B       0.68      0.63      0.65        51
           C       0.55      0.76      0.64        38
           F       0.00      0.00      0.00         6

    accuracy                           0.61       101
   macro avg       0.56      0.39      0.39       101
weighted avg       0.61      0.61      0.59       101

[[ 1  5  0  0]
 [ 0 32 19  0]
 [ 0  9 29  0]
 [ 0  1  5  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### NAIVE BAYES

In [22]:
from sklearn.naive_bayes import GaussianNB

naive_bayes_model = GaussianNB()
naive_bayes_model.fit(x_train, y_train)

y_pred = naive_bayes_model.predict(x_test)

# Menampilkan laporan klasifikasi dan matriks kebingungan
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report:
               precision    recall  f1-score   support

           A       0.67      0.67      0.67         6
           B       0.72      0.55      0.62        51
           C       0.52      0.76      0.62        38
           F       0.00      0.00      0.00         6

    accuracy                           0.60       101
   macro avg       0.48      0.49      0.48       101
weighted avg       0.60      0.60      0.59       101

Confusion Matrix:
 [[ 4  2  0  0]
 [ 2 28 21  0]
 [ 0  9 29  0]
 [ 0  0  6  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
import joblib
# Save the model to a file
joblib.dump(naive_bayes_model, 'microbiology.joblib')

# Load the model from the file
loaded_model = joblib.load('microbiology.joblib')

In [24]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Definisikan model Naive Bayes
naive_bayes_model = GaussianNB()

# Parameter yang ingin dioptimalkan (hanya var_smoothing pada Gaussian Naive Bayes)
param_grid = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(naive_bayes_model, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_naive_bayes_model = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_naive_bayes_model.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_naive_bayes_model.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Best Parameters: {'var_smoothing': 1e-09}
Classification Report:
               precision    recall  f1-score   support

           A       0.67      0.67      0.67         6
           B       0.72      0.55      0.62        51
           C       0.52      0.76      0.62        38
           F       0.00      0.00      0.00         6

    accuracy                           0.60       101
   macro avg       0.48      0.49      0.48       101
weighted avg       0.60      0.60      0.59       101

Confusion Matrix:
 [[ 4  2  0  0]
 [ 2 28 21  0]
 [ 0  9 29  0]
 [ 0  0  6  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###NEURAL NETWORK

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Standarisasi data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Menggunakan LabelEncoder untuk mengonversi label menjadi format numerik
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# Membangun model neural network
model = Sequential()
model.add(Dense(64, input_dim=x_train_scaled.shape[1], activation='relu'))  # Layer input
model.add(Dense(32, activation='relu'))  # Hidden layer
model.add(Dense(1, activation='sigmoid'))  # Layer output, output biner sehingga menggunakan sigmoid

# Kompilasi model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Melatih model
model.fit(x_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(x_test_scaled, y_test))

# Evaluasi model
eval_result = model.evaluate(x_test_scaled, y_test)
print(f'\nTest Loss: {eval_result[0]}, Test Accuracy: {eval_result[1]}')

# Prediksi
y_pred = (model.predict(x_test_scaled) > 0.5).astype("int32")

# Menampilkan hasil evaluasi model
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Epoch 1/10
5/5 [==============================] - 1s 62ms/step - loss: 0.5872 - accuracy: 0.3200 - val_loss: 0.3857 - val_accuracy: 0.3465
Epoch 2/10
5/5 [==============================] - 0s 14ms/step - loss: 0.4259 - accuracy: 0.3733 - val_loss: 0.1939 - val_accuracy: 0.4356
Epoch 3/10
5/5 [==============================] - 0s 12ms/step - loss: 0.2810 - accuracy: 0.4867 - val_loss: 0.0073 - val_accuracy: 0.5050
Epoch 4/10
5/5 [==============================] - 0s 16ms/step - loss: 0.1388 - accuracy: 0.5333 - val_loss: -0.1760 - val_accuracy: 0.5050
Epoch 5/10
5/5 [==============================] - 0s 14ms/step - loss: -0.0022 - accuracy: 0.5267 - val_loss: -0.3610 - val_accuracy: 0.5050
Epoch 6/10
5/5 [==============================] - 0s 14ms/step - loss: -0.1455 - accuracy: 0.5267 - val_loss: -0.5527 - val_accuracy: 0.5050
Epoch 7/10
5/5 [==============================] - 0s 12ms/step - loss: -0.2894 - accuracy: 0.5267 - val_loss: -0.7595 - val_accuracy: 0.5050
Epoch 8/10
5/5 [====

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###xgb

In [26]:
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix

# Initialize XGBoost classifier
xgb_clf = xgb.XGBClassifier(random_state=2022)

# Fit the model on the training data
xgb_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = xgb_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       0.62      0.67      0.64        51
           2       0.53      0.63      0.58        38
           3       0.00      0.00      0.00         6

    accuracy                           0.57       101
   macro avg       0.29      0.32      0.30       101
weighted avg       0.51      0.57      0.54       101

Confusion Matrix:
[[ 0  6  0  0]
 [ 1 34 16  0]
 [ 0 14 24  0]
 [ 0  1  5  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# CatBoost

In [27]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 MB 8.6 MB/s eta 0:00:00


In [28]:
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize CatBoost classifier
catboost_clf = CatBoostClassifier()

# Fit the model on the training data
catboost_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = catboost_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Learning rate set to 0.07183
0:	learn: 1.3314509	total: 58.4ms	remaining: 58.3s
1:	learn: 1.2891180	total: 66.2ms	remaining: 33s
2:	learn: 1.2490248	total: 71.4ms	remaining: 23.7s
3:	learn: 1.2066808	total: 76.7ms	remaining: 19.1s
4:	learn: 1.1693749	total: 82.7ms	remaining: 16.5s
5:	learn: 1.1359420	total: 86.1ms	remaining: 14.3s
6:	learn: 1.1040365	total: 91.7ms	remaining: 13s
7:	learn: 1.0801141	total: 96.5ms	remaining: 12s
8:	learn: 1.0582316	total: 102ms	remaining: 11.2s
9:	learn: 1.0342107	total: 106ms	remaining: 10.4s
10:	learn: 1.0109591	total: 108ms	remaining: 9.74s
11:	learn: 0.9888348	total: 111ms	remaining: 9.12s
12:	learn: 0.9647344	total: 113ms	remaining: 8.61s
13:	learn: 0.9420022	total: 115ms	remaining: 8.11s
14:	learn: 0.9244378	total: 118ms	remaining: 7.76s
15:	learn: 0.9086662	total: 121ms	remaining: 7.43s
16:	learn: 0.8936509	total: 124ms	remaining: 7.15s
17:	learn: 0.8808551	total: 126ms	remaining: 6.85s
18:	learn: 0.8687734	total: 128ms	remaining: 6.61s
19:	learn:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###K-NN

In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize KNN classifier
knn_clf = KNeighborsClassifier()

# Fit the model on the training data
knn_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = knn_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       0.65      0.80      0.72        51
           2       0.61      0.61      0.61        38
           3       0.00      0.00      0.00         6

    accuracy                           0.63       101
   macro avg       0.31      0.35      0.33       101
weighted avg       0.56      0.63      0.59       101

Confusion Matrix:
[[ 0  5  1  0]
 [ 0 41 10  0]
 [ 0 15 23  0]
 [ 0  2  4  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###ADABOOST

In [30]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize AdaBoost classifier
ada_clf = AdaBoostClassifier(random_state=2022)

# Fit the model on the training data
ada_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = ada_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.38      0.50      0.43         6
           1       0.61      0.49      0.54        51
           2       0.48      0.66      0.56        38
           3       0.00      0.00      0.00         6

    accuracy                           0.52       101
   macro avg       0.37      0.41      0.38       101
weighted avg       0.51      0.52      0.51       101

Confusion Matrix:
[[ 3  2  1  0]
 [ 5 25 21  0]
 [ 0 13 25  0]
 [ 0  1  5  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
!pip install catboost

In [32]:
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize CatBoost classifier
catboost_clf = CatBoostClassifier()

# Fit the model on the training data
catboost_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = catboost_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Learning rate set to 0.07183
0:	learn: 1.3314509	total: 6.67ms	remaining: 6.66s
1:	learn: 1.2891180	total: 12ms	remaining: 5.98s
2:	learn: 1.2490248	total: 17ms	remaining: 5.66s
3:	learn: 1.2066808	total: 20.6ms	remaining: 5.13s
4:	learn: 1.1693749	total: 26.8ms	remaining: 5.33s
5:	learn: 1.1359420	total: 31.7ms	remaining: 5.24s
6:	learn: 1.1040365	total: 38.1ms	remaining: 5.4s
7:	learn: 1.0801141	total: 46ms	remaining: 5.7s
8:	learn: 1.0582316	total: 52.5ms	remaining: 5.79s
9:	learn: 1.0342107	total: 55.7ms	remaining: 5.52s
10:	learn: 1.0109591	total: 61.5ms	remaining: 5.53s
11:	learn: 0.9888348	total: 66.3ms	remaining: 5.46s
12:	learn: 0.9647344	total: 71.7ms	remaining: 5.45s
13:	learn: 0.9420022	total: 84.9ms	remaining: 5.98s
14:	learn: 0.9244378	total: 90.6ms	remaining: 5.95s
15:	learn: 0.9086662	total: 92.6ms	remaining: 5.69s
16:	learn: 0.8936509	total: 94.8ms	remaining: 5.48s
17:	learn: 0.8808551	total: 98.4ms	remaining: 5.37s
18:	learn: 0.8687734	total: 108ms	remaining: 5.55s
19

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
