**YEAR 2-4** **DENTAL MATERIAL SCIENCE MARK**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_excel('/content/drive/MyDrive/Trek AI/Y2-Data.xlsx')

In [4]:
# Kolom yang akan digunakan untuk klasifikasi
grading_columns = ['PATHOLOGY MARK', 'MICROBIOLOGY MARK', 'PHARMACOLOGY MARK', 'DENTAL MATERIAL SCIENCE MARK ']

# Fungsi untuk mengklasifikasikan nilai menjadi kategori
def classify_grades(score):
    # Mengonversi nilai ke tipe data numerik jika belum
    try:
        score = float(score)
    except ValueError:
        return 'Invalid Score'  # Atau tindakan yang sesuai jika nilai tidak dapat dikonversi

    if score >= 75:
        return 'A'
    elif 60 <= score < 75:
        return 'B'
    elif 50 <= score < 60:
        return 'C'
    else:
        return 'F'

# Iterasi melalui kolom-kolom yang akan dijadikan dasar klasifikasi
for column in grading_columns:
    # Membuat kolom baru dengan nama yang dihasilkan dari kolom asli ditambah '_GRADE'
    new_column_name = column + '_GRADE'
    df[new_column_name] = df[column].apply(classify_grades)

# Tampilkan DataFrame yang sudah dimodifikasi
print(df)


    STUDENT'S IDENTITY NO.   LAST DIGIT MATRIC NO.  AGE DURING ADMISSION  \
0                  12-13-01                      8                    21   
1                  12-13-02                      6                    20   
2                  12-13-03                      6                    20   
3                  12-13-04                      4                    20   
4                  12-13-05                      6                    20   
..                      ...                    ...                   ...   
246                16-17-51                      5                    20   
247                16-17-52                      4                    20   
248                16-17-53                      4                    20   
249                16-17-55                      2                    20   
250                16-17-56                      4                    19   

    BIRTH DATE MIDDLE IC NO.          DISTRICT POSCODE       STATE   COUNTRY  \
0      

In [5]:
df.isnull().sum()

STUDENT'S IDENTITY NO.                 0
LAST DIGIT MATRIC NO.                  0
AGE DURING ADMISSION                   0
BIRTH DATE                             0
MIDDLE IC NO.                          0
DISTRICT                               0
POSCODE                                0
STATE                                  0
COUNTRY                                0
PRE-UNIVERSITY                         0
TOTAL_SEM                              0
AVERAGE_CGPA                           0
FINAL_CGPA                             0
ANATOMY MARK                           0
ANATOMY STATUS                         0
PHYSIOLOGY MARK                        0
PHYSIOLOGY STATUS                      0
BIOCHEMISTRY MARK                      0
BIOCHEMISTRY STATUS                    0
ORAL BIOLOGY MARK                      0
ORAL BIOLOGY STATUS                    0
PATHOLOGY MARK                         0
PATHOLOGY STATUS                       0
MICROBIOLOGY MARK                      0
MICROBIOLOGY STA

In [6]:
df.head()

STUDENT'S IDENTITY NO.   LAST DIGIT MATRIC NO.  AGE DURING ADMISSION  \
0                12-13-01                      8                    21   
1                12-13-02                      6                    20   
2                12-13-03                      6                    20   
3                12-13-04                      4                    20   
4                12-13-05                      6                    20   

  BIRTH DATE MIDDLE IC NO.    DISTRICT POSCODE     STATE   COUNTRY  \
0     911122            14  KOTA BHARU   43000  SELANGOR  MALAYSIA   
1     920816             3      BACHOK   16370  KELANTAN  MALAYSIA   
2     920522             6    JERANTUT   27020    PAHANG  MALAYSIA   
3     920625             8     PUCHONG   47100  SELANGOR  MALAYSIA   
4     920126            10      KAJANG   43000  SELANGOR  MALAYSIA   

  PRE-UNIVERSITY  ...  PHARMACOLOGY STATUS  DENTAL MATERIAL SCIENCE MARK   \
0       CFS IIUM  ...                 PASS                      52.837500   
1       CFS IIUM  ...                 FAIL                      59.316667   
2       CFS IIUM  ...                 PASS                      54.875000   
3       CFS IIUM  ...                 PASS                      59.625000   
4       CFS IIUM  ...                 PASS                      59.629167   

   DENTAL MATERIAL SCIENCE STATUS               Batch REPEAT PAPER  \
0                            PASS  batch1213_combined           NO   
1                            PASS  batch1213_combined           NO   
2                            PASS  batch1213_combined           NO   
3                            PASS  batch1213_combined           NO   
4                            PASS  batch1213_combined           NO   

   GENDER_MALE PATHOLOGY MARK_GRADE  MICROBIOLOGY MARK_GRADE  \
0            0                    C                        C   
1            0                    F                        C   
2            0                    F                        C   
3            0                    C                        B   
4            0                    C                        F   

  PHARMACOLOGY MARK_GRADE  DENTAL MATERIAL SCIENCE MARK _GRADE  
0                       C                                    C  
1                       F                                    C  
2                       C                                    C  
3                       C                                    C  
4                       C                                    C  

[5 rows x 36 columns]

In [7]:
from sklearn.feature_selection import SelectKBest, f_classif

x = df.drop(["STUDENT'S IDENTITY NO. ", 'ANATOMY STATUS', 'PHYSIOLOGY STATUS', 'BIOCHEMISTRY STATUS',
             'ORAL BIOLOGY STATUS', 'PATHOLOGY MARK', 'PATHOLOGY STATUS', 'Batch', 'REPEAT PAPER',
             'MICROBIOLOGY MARK', 'MICROBIOLOGY STATUS', 'PHARMACOLOGY MARK',
             'PHARMACOLOGY STATUS', 'DENTAL MATERIAL SCIENCE MARK ',
             'DENTAL MATERIAL SCIENCE STATUS', 'BIRTH DATE','MIDDLE IC NO.',
             'DISTRICT','POSCODE', 'STATE', 'COUNTRY', 'PRE-UNIVERSITY','LAST DIGIT MATRIC NO.', 'GENDER_MALE', 'PATHOLOGY MARK_GRADE',
             'MICROBIOLOGY MARK_GRADE', 'PHARMACOLOGY MARK_GRADE', 'DENTAL MATERIAL SCIENCE MARK _GRADE'], axis=1)
y = df['DENTAL MATERIAL SCIENCE MARK _GRADE']

k_best = 4  # Ganti dengan jumlah fitur terbaik yang ingin Anda pilih
selector = SelectKBest(score_func=f_classif, k=k_best)
x_new = selector.fit_transform(x, y)

# Menampilkan fitur terpilih
selected_features = x.columns[selector.get_support()]
print("Selected Features:", selected_features)

Selected Features: Index(['ANATOMY MARK', 'PHYSIOLOGY MARK', 'BIOCHEMISTRY MARK',
       'ORAL BIOLOGY MARK'],
      dtype='object')


In [8]:
df.columns

Index(['STUDENT'S IDENTITY NO. ', 'LAST DIGIT MATRIC NO.',
       'AGE DURING ADMISSION', 'BIRTH DATE', 'MIDDLE IC NO.', 'DISTRICT',
       'POSCODE', 'STATE', 'COUNTRY', 'PRE-UNIVERSITY', 'TOTAL_SEM',
       'AVERAGE_CGPA', 'FINAL_CGPA', 'ANATOMY MARK', 'ANATOMY STATUS',
       'PHYSIOLOGY MARK', 'PHYSIOLOGY STATUS', 'BIOCHEMISTRY MARK',
       'BIOCHEMISTRY STATUS', 'ORAL BIOLOGY MARK', 'ORAL BIOLOGY STATUS',
       'PATHOLOGY MARK', 'PATHOLOGY STATUS', 'MICROBIOLOGY MARK',
       'MICROBIOLOGY STATUS', 'PHARMACOLOGY MARK', 'PHARMACOLOGY STATUS',
       'DENTAL MATERIAL SCIENCE MARK ', 'DENTAL MATERIAL SCIENCE STATUS',
       'Batch', 'REPEAT PAPER', 'GENDER_MALE', 'PATHOLOGY MARK_GRADE',
       'MICROBIOLOGY MARK_GRADE', 'PHARMACOLOGY MARK_GRADE',
       'DENTAL MATERIAL SCIENCE MARK _GRADE'],
      dtype='object')

In [9]:
y = df['DENTAL MATERIAL SCIENCE MARK _GRADE']
y.value_counts()

DENTAL MATERIAL SCIENCE MARK _GRADE
B    140
C     97
A      9
F      5
Name: count, dtype: int64

In [10]:
# Memisahkan data menjadi data training dan data testing menjadi 60% data training, 40% data testing
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.4,
                                                   random_state = 2022)

In [11]:
y_train.value_counts()

DENTAL MATERIAL SCIENCE MARK _GRADE
B    87
C    54
A     6
F     3
Name: count, dtype: int64

In [12]:
y_test.value_counts()

DENTAL MATERIAL SCIENCE MARK _GRADE
B    53
C    43
A     3
F     2
Name: count, dtype: int64

# Modelling

## Logistic Regression

In [13]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix

# Model Development
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(random_state=2022)
log_reg.fit(x_train, y_train)

y_pred = log_reg.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.00      0.00      0.00         3
           B       0.54      0.96      0.69        53
           C       0.67      0.09      0.16        43
           F       0.00      0.00      0.00         2

    accuracy                           0.54       101
   macro avg       0.30      0.26      0.21       101
weighted avg       0.57      0.54      0.43       101

[[ 0  3  0  0]
 [ 0 51  2  0]
 [ 1 38  4  0]
 [ 0  2  0  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit

In [14]:
from sklearn.model_selection import GridSearchCV

# Definisi model Logistic Regression
log_reg = LogisticRegression(random_state=2022)

# Tentukan daftar hyperparameter yang ingin diuji
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2']
}

# Inisialisasi GridSearchCV dengan model, hyperparameter grid, dan jumlah lipatan cross-validation
grid_search = GridSearchCV(log_reg, param_grid, cv=5, scoring='accuracy')

# Latih model dengan melakukan pencarian grid
grid_search.fit(x_train, y_train)

# Cetak hyperparameter terbaik yang ditemukan
print("Best hyperparameters:", grid_search.best_params_)

# Gunakan model dengan hyperparameter terbaik untuk membuat prediksi pada data testing
y_pred_log_tuned = grid_search.best_estimator_.predict(x_test)

# Cetak laporan klasifikasi dan matriks kebingungan
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log_tuned))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_log_tuned))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modu

Best hyperparameters: {'C': 0.01, 'penalty': 'l2'}

Classification Report:
              precision    recall  f1-score   support

           A       0.00      0.00      0.00         3
           B       0.69      0.79      0.74        53
           C       0.70      0.65      0.67        43
           F       0.00      0.00      0.00         2

    accuracy                           0.69       101
   macro avg       0.35      0.36      0.35       101
weighted avg       0.66      0.69      0.67       101


Confusion Matrix:
[[ 0  3  0  0]
 [ 0 42 11  0]
 [ 0 15 28  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

## Decision Tree

In [15]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(random_state= 2022)
clf = clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.50      0.33      0.40         3
           B       0.55      0.60      0.58        53
           C       0.45      0.40      0.42        43
           F       0.00      0.00      0.00         2

    accuracy                           0.50       101
   macro avg       0.37      0.33      0.35       101
weighted avg       0.49      0.50      0.49       101

[[ 1  2  0  0]
 [ 1 32 20  0]
 [ 0 23 17  3]
 [ 0  1  1  0]]


In [16]:
from sklearn.model_selection import GridSearchCV

# Definisikan model Decision Tree
clf = tree.DecisionTreeClassifier(random_state=2022)

# Tentukan hyperparameter yang akan dioptimalkan
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_clf = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_clf.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_clf.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5}
Classification Report:
               precision    recall  f1-score   support

           A       0.50      0.33      0.40         3
           B       0.62      0.68      0.65        53
           C       0.56      0.53      0.55        43
           F       0.00      0.00      0.00         2

    accuracy                           0.59       101
   macro avg       0.42      0.39      0.40       101
weighted avg       0.58      0.59      0.59       101

Confusion Matrix:
 [[ 1  2  0  0]
 [ 1 36 16  0]
 [ 0 20 23  0]
 [ 0  0  2  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Random Forest

In [17]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state= 2022)
clf = clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       1.00      0.33      0.50         3
           B       0.65      0.74      0.69        53
           C       0.62      0.58      0.60        43
           F       0.00      0.00      0.00         2

    accuracy                           0.64       101
   macro avg       0.57      0.41      0.45       101
weighted avg       0.64      0.64      0.63       101

[[ 1  2  0  0]
 [ 0 39 14  0]
 [ 0 18 25  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Definisikan model Random Forest
clf = RandomForestClassifier(random_state=2022)

# Tentukan hyperparameter yang akan dioptimalkan
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_clf = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_clf.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_clf.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'`

Best Parameters: {'max_depth': 10, 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 50}
Classification Report:
               precision    recall  f1-score   support

           A       1.00      0.33      0.50         3
           B       0.65      0.75      0.70        53
           C       0.63      0.56      0.59        43
           F       0.00      0.00      0.00         2

    accuracy                           0.64       101
   macro avg       0.57      0.41      0.45       101
weighted avg       0.64      0.64      0.63       101

Confusion Matrix:
 [[ 1  2  0  0]
 [ 0 40 13  0]
 [ 0 19 24  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, l

## Support Vector Machine (SVM)

In [19]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
y_pred

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.00      0.00      0.00         3
           B       0.65      0.83      0.73        53
           C       0.70      0.53      0.61        43
           F       0.00      0.00      0.00         2

    accuracy                           0.66       101
   macro avg       0.34      0.34      0.33       101
weighted avg       0.64      0.66      0.64       101

[[ 0  3  0  0]
 [ 0 44  9  0]
 [ 0 20 23  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Definisikan model SVM
clf = make_pipeline(StandardScaler(), SVC())

# Tentukan hyperparameter yang akan dioptimalkan
param_grid = {
    'svc__C': [0.1, 1, 10, 100],
    'svc__gamma': ['scale', 'auto', 0.1, 1, 10]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_clf = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_clf.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_clf.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'svc__C': 1, 'svc__gamma': 1}
Classification Report:
               precision    recall  f1-score   support

           A       0.00      0.00      0.00         3
           B       0.65      0.79      0.71        53
           C       0.67      0.56      0.61        43
           F       0.00      0.00      0.00         2

    accuracy                           0.65       101
   macro avg       0.33      0.34      0.33       101
weighted avg       0.62      0.65      0.63       101

Confusion Matrix:
 [[ 0  3  0  0]
 [ 0 42 11  0]
 [ 0 19 24  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Naive Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB

naive_bayes_model = GaussianNB()
naive_bayes_model.fit(x_train, y_train)

y_pred = naive_bayes_model.predict(x_test)

# Menampilkan laporan klasifikasi dan matriks kebingungan
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           A       0.67      0.67      0.67         3
           B       0.77      0.62      0.69        53
           C       0.63      0.79      0.70        43
           F       0.00      0.00      0.00         2

    accuracy                           0.68       101
   macro avg       0.52      0.52      0.51       101
weighted avg       0.69      0.68      0.68       101

Confusion Matrix:
 [[ 2  1  0  0]
 [ 1 33 18  1]
 [ 0  9 34  0]
 [ 0  0  2  0]]


In [22]:
import joblib
# Save the model to a file
joblib.dump(naive_bayes_model, 'Dental_Material_Science.joblib')

# Load the model from the file
loaded_model = joblib.load('Dental_Material_Science.joblib')

In [24]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Definisikan model Naive Bayes
naive_bayes_model = GaussianNB()

# Parameter yang ingin dioptimalkan (hanya var_smoothing pada Gaussian Naive Bayes)
param_grid = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(naive_bayes_model, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_naive_bayes_model = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_naive_bayes_model.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_naive_bayes_model.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'var_smoothing': 1e-09}
Classification Report:
               precision    recall  f1-score   support

           A       0.67      0.67      0.67         3
           B       0.77      0.62      0.69        53
           C       0.63      0.79      0.70        43
           F       0.00      0.00      0.00         2

    accuracy                           0.68       101
   macro avg       0.52      0.52      0.51       101
weighted avg       0.69      0.68      0.68       101

Confusion Matrix:
 [[ 2  1  0  0]
 [ 1 33 18  1]
 [ 0  9 34  0]
 [ 0  0  2  0]]


## Neural Networks

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Standarisasi data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Menggunakan LabelEncoder untuk mengonversi label menjadi format numerik
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# Membangun model neural network
model = Sequential()
model.add(Dense(64, input_dim=x_train_scaled.shape[1], activation='relu'))  # Layer input
model.add(Dense(32, activation='relu'))  # Hidden layer
model.add(Dense(1, activation='sigmoid'))  # Layer output, output biner sehingga menggunakan sigmoid

# Kompilasi model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Melatih model
model.fit(x_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(x_test_scaled, y_test))

# Evaluasi model
eval_result = model.evaluate(x_test_scaled, y_test)
print(f'\nTest Loss: {eval_result[0]}, Test Accuracy: {eval_result[1]}')

# Prediksi
y_pred = (model.predict(x_test_scaled) > 0.5).astype("int32")

# Menampilkan hasil evaluasi model
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Epoch 1/10
5/5 [==============================] - 1s 66ms/step - loss: 0.5606 - accuracy: 0.4400 - val_loss: 0.4131 - val_accuracy: 0.5149
Epoch 2/10
5/5 [==============================] - 0s 11ms/step - loss: 0.4040 - accuracy: 0.5800 - val_loss: 0.2514 - val_accuracy: 0.5248
Epoch 3/10
5/5 [==============================] - 0s 16ms/step - loss: 0.2639 - accuracy: 0.5800 - val_loss: 0.1048 - val_accuracy: 0.5248
Epoch 4/10
5/5 [==============================] - 0s 11ms/step - loss: 0.1466 - accuracy: 0.5800 - val_loss: -0.0363 - val_accuracy: 0.5248
Epoch 5/10
5/5 [==============================] - 0s 11ms/step - loss: 0.0249 - accuracy: 0.5800 - val_loss: -0.1788 - val_accuracy: 0.5248
Epoch 6/10
5/5 [==============================] - 0s 15ms/step - loss: -0.0925 - accuracy: 0.5800 - val_loss: -0.3366 - val_accuracy: 0.5248
Epoch 7/10
5/5 [==============================] - 0s 14ms/step - loss: -0.2284 - accuracy: 0.5800 - val_loss: -0.5091 - val_accuracy: 0.5248
Epoch 8/10
5/5 [=====

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## XGBOOST

In [26]:
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix

# Initialize XGBoost classifier
xgb_clf = xgb.XGBClassifier(random_state=2022)

# Fit the model on the training data
xgb_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = xgb_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.61      0.64      0.62        53
           2       0.55      0.56      0.55        43
           3       0.00      0.00      0.00         2

    accuracy                           0.57       101
   macro avg       0.29      0.30      0.29       101
weighted avg       0.55      0.57      0.56       101

Confusion Matrix:
[[ 0  3  0  0]
 [ 0 34 18  1]
 [ 0 19 24  0]
 [ 0  0  2  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize KNN classifier
knn_clf = KNeighborsClassifier()

# Fit the model on the training data
knn_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = knn_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.62      0.68      0.65        53
           2       0.59      0.56      0.57        43
           3       0.00      0.00      0.00         2

    accuracy                           0.59       101
   macro avg       0.30      0.31      0.31       101
weighted avg       0.57      0.59      0.58       101

Confusion Matrix:
[[ 0  3  0  0]
 [ 2 36 15  0]
 [ 0 19 24  0]
 [ 0  0  2  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Initialize KNN classifier
knn_clf = KNeighborsClassifier()

# Tentukan hyperparameter yang akan dioptimalkan
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'p': [1, 2]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(knn_clf, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_knn_clf = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_knn_clf.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_knn_clf.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'algorithm': 'auto', 'n_neighbors': 9, 'p': 1, 'weights': 'uniform'}
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.64      0.77      0.70        53
           2       0.65      0.56      0.60        43
           3       0.00      0.00      0.00         2

    accuracy                           0.64       101
   macro avg       0.32      0.33      0.33       101
weighted avg       0.61      0.64      0.62       101

Confusion Matrix:
 [[ 0  3  0  0]
 [ 0 41 12  0]
 [ 0 19 24  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## CATBOOST

In [30]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 MB 2.1 MB/s eta 0:00:00


In [31]:
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize CatBoost classifier
catboost_clf = CatBoostClassifier()

# Fit the model on the training data
catboost_clf.fit(x_train, y_train)

# Predict on the test set
y_pred = catboost_clf.predict(x_test)

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Learning rate set to 0.07183
0:	learn: 1.3249858	total: 53.1ms	remaining: 53s
1:	learn: 1.2733554	total: 59ms	remaining: 29.5s
2:	learn: 1.2301902	total: 63ms	remaining: 20.9s
3:	learn: 1.1896059	total: 68.7ms	remaining: 17.1s
4:	learn: 1.1485653	total: 79.2ms	remaining: 15.8s
5:	learn: 1.1103426	total: 84.4ms	remaining: 14s
6:	learn: 1.0788876	total: 89.8ms	remaining: 12.7s
7:	learn: 1.0524385	total: 95.2ms	remaining: 11.8s
8:	learn: 1.0271113	total: 101ms	remaining: 11.1s
9:	learn: 1.0016941	total: 106ms	remaining: 10.5s
10:	learn: 0.9786155	total: 111ms	remaining: 10s
11:	learn: 0.9566190	total: 116ms	remaining: 9.56s
12:	learn: 0.9337538	total: 122ms	remaining: 9.23s
13:	learn: 0.9129325	total: 126ms	remaining: 8.9s
14:	learn: 0.8947766	total: 132ms	remaining: 8.66s
15:	learn: 0.8784338	total: 137ms	remaining: 8.4s
16:	learn: 0.8640884	total: 142ms	remaining: 8.24s
17:	learn: 0.8498588	total: 146ms	remaining: 7.94s
18:	learn: 0.8354385	total: 151ms	remaining: 7.82s
19:	learn: 0.818

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## ADABOOST

In [32]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Initialize AdaBoost classifier
ada_clf = AdaBoostClassifier(random_state=2022)

# Tentukan hyperparameter yang akan dioptimalkan
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2, 0.5, 1.0]
}

# Gunakan GridSearchCV untuk mencari kombinasi hyperparameter terbaik
grid_search = GridSearchCV(ada_clf, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)

# Ambil model dengan kombinasi hyperparameter terbaik
best_ada_clf = grid_search.best_estimator_

# Latih model dengan data pelatihan
best_ada_clf.fit(x_train, y_train)

# Prediksi menggunakan model yang dioptimalkan
y_pred = best_ada_clf.predict(x_test)

# Tampilkan hasil evaluasi
print("Best Parameters:", grid_search.best_params_)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'learning_rate': 0.01, 'n_estimators': 50}
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.59      0.91      0.72        53
           2       0.70      0.33      0.44        43
           3       0.00      0.00      0.00         2

    accuracy                           0.61       101
   macro avg       0.32      0.31      0.29       101
weighted avg       0.61      0.61      0.57       101

Confusion Matrix:
 [[ 0  3  0  0]
 [ 0 48  5  0]
 [ 0 29 14  0]
 [ 0  1  1  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
